# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AmbientOrb-Serial
version:      0.02
version_from: lib/AmbientOrb/Serial.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor:               0
    Test::More:                    0
    Win32::SerialPort:             0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
